### ISSUE TITLE
hasSize - NoSuchMethodError

### ISSUE THREAD

**Issue by aponhcet** [googleads/googleads-java-lib#105]
Hi there,
Using version   
     <dependency>
            <groupId>com.google.truth</groupId>
            <artifactId>truth</artifactId>
            <version>0.31</version>
            <scope>test</scope>
        </dependency>
When asserting the size of a collection - I tried ArrayList and SortedMap - I got the following error. 

Downgrading to 0.30 fix it.

java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V

	at com.google.common.truth.FailureContext.<init>(FailureContext.java:40)
	at com.google.common.truth.AbstractVerb.<init>(AbstractVerb.java:35)
	at com.google.common.truth.TestVerb.<init>(TestVerb.java:49)
	at com.google.common.truth.TestVerb.<init>(TestVerb.java:41)
	at com.google.common.truth.TestVerb.<init>(TestVerb.java:37)
	at com.google.common.truth.Truth.<clinit>(Truth.java:76)
	at

**Comment by jradcliff** [comment]
Hi,

This looks like an issue with the `google/truth` project. Could you file this via [that project's issue tracker](https://github.com/google/truth/issues) instead?

Thanks,
Josh, AdWords API Team
