### ISSUE TITLE
No group found for service

### ISSUE THREAD

**Issue by srinivasgiduthuri** [googleads/googleads-java-lib#143]
Hello team,

I am getting the following exception while creating the service object. Could someone help me what's wrong with this? When can this happen?

This was coming since I upgraded the AdWords library from 201710 to 201802.

Caused by: java.lang.NullPointerException: No group found for service: v201802.AdwordsUserListService
	at com.google.api.ads.adwords.lib.conf.AdWordsApiConfiguration.getServiceUrlGroup(AdWordsApiConfiguration.java:52) ~[ads-lib-3.14.1.jar:?]
	at com.google.api.ads.adwords.lib.client.AdWordsServiceDescriptor.getEndpointAddress(AdWordsServiceDescriptor.java:77) ~[ads-lib-3.14.1.jar:?]
	at com.google.api.ads.common.lib.factory.helper.BaseAdsServiceClientFactoryHelper.createAdsServiceClient(BaseAdsServiceClientFactoryHelper.java:73) ~[ads-lib-3.14.1.jar:?]
	at com.google.api.ads.common.lib.factory.AdsServiceClientFactory.getServiceClient(AdsServiceClientFactory.java:76) ~[ads-lib-3.14.1.jar:?]
	at com.google.api.ads.common.lib.factory.BaseAdsServiceClientFactory.getServiceClientAsInterface(BaseAdsServiceClientFactory.java:81) ~[ads-lib-3.14.1.jar:?]
	at com.google.api.ads.common.lib.factory.BaseServices.get(BaseServices.java:45) ~[ads-lib-3.14.1.jar:?]

Thanks,
Srinivas

**Comment by srinivasgiduthuri** [comment]
I am importing the following libraries as dependencies manually(not using maven) by executing the build command "mvn clean compile package".

ads-lib-3.14.1.jar
ads-lib-axis-3.14.1.jar
adwords-axis-3.14.1.jar

Am I missing any other libraries?

**Comment by jradcliff** [comment]
Hi,

The `adwords-axis-jars-and-examples` download under the [3.14.1 release](https://github.com/googleads/googleads-java-lib/releases/tag/3.14.1) contains a `lib` directory with all required dependencies. Could you make sure you're including all of those in your classpath?

Thanks,
Josh, AdWords API Team

**Comment by srinivasgiduthuri** [comment]
Hello @jradcliff 

Thanks for your response. I will check all the dependencies that are mentioned in the lib as you said. Will get back to you once I have done that.

Thanks,
Srinivas

**Comment by srinivasgiduthuri** [comment]
Hello @jradcliff 

We are using guava-19.0 in our entire application. Due to other dependencies, we cannot upgrade to 20.0. I have tested by upgrading guava to 20.0. It worked fine. After downgrading the guava library to 19.0, I am facing a new issue which NoClassDefFoundError.

Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.google.api.ads.common.lib.auth.OfflineCredentials$Api

Could you please throw some light on this?

Thanks,
Srinivas

**Comment by jradcliff** [comment]
Hi,

Could you let me know which version of the library you were using with v201710? I ask because the library has had a dependency on Guava 20.0 for over a year (since [release 3.1.1](https://github.com/googleads/googleads-java-lib/releases/tag/3.1.1)), so I'm surprised you didn't hit this error earlier.

Thanks,
Josh, AdWords API Team
