### ISSUE TITLE
Inconsistent SAXException coming from AdgroupAdService

### ISSUE THREAD

**Issue by TheCodeNinja** [googleads/googleads-java-lib#146]
Re-posting this issue here as the folks on the forum told me this was a better place for it.

I am trying to list ads for an adgroup using the Java Adwords sdk and am getting the exception below. I've traced it all the way down in the debugger, and the call to the API is successful, but the Adwords library is failing to deserialize the response from the API. It only happens for some adgroups/clients...I'm thinking this is a bug in the API but not sure. Has anyone had this issue before or have any insight into why it happens/how to fix it?

` org.xml.sax.SAXException: SimpleDeserializer encountered a child element, which is NOT expected, in something it was trying to deserialize.
	at org.apache.axis.encoding.ser.SimpleDeserializer.onStartChild(SimpleDeserializer.java:145) ~[axis-1.4.jar:?]
	at org.apache.axis.encoding.DeserializationContext.startElement(DeserializationContext.java:1035) ~[axis-1.4.jar:?]
	at org.apache.axis.message.SAX2EventRecorder.replay(SAX2EventRecorder.java:165) ~[axis-1.4.jar:?]
	at org.apache.axis.message.MessageElement.publishToHandler(MessageElement.java:1141) ~[axis-1.4.jar:?]
	at org.apache.axis.message.RPCElement.deserialize(RPCElement.java:236) ~[axis-1.4.jar:?]
	at org.apache.axis.message.RPCElement.getParams(RPCElement.java:384) ~[axis-1.4.jar:?]
	at org.apache.axis.client.Call.invoke(Call.java:2467) ~[axis-1.4.jar:?]
	at org.apache.axis.client.Call.invoke(Call.java:2366) ~[axis-1.4.jar:?]
	at org.apache.axis.client.Call.invoke(Call.java:1812) ~[axis-1.4.jar:?]
	at com.google.api.ads.adwords.axis.v201806.cm.AdGroupAdServiceSoapBindingStub.get(AdGroupAdServiceSoapBindingStub.java:1751) ~[adwords-axis-3.15.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.google.api.ads.common.lib.soap.SoapClientHandler.invoke(SoapClientHandler.java:100) ~[ads-lib-3.15.0.jar:?]
	at com.google.api.ads.common.lib.soap.axis.AxisHandler.invokeSoapCall(AxisHandler.java:234) ~[ads-lib-axis-3.15.0.jar:?]
	at com.google.api.ads.common.lib.soap.SoapServiceClient.callSoapClient(SoapServiceClient.java:63) ~[ads-lib-3.15.0.jar:?]
	at com.google.api.ads.common.lib.soap.SoapServiceClient.invoke(SoapServiceClient.java:93) ~[ads-lib-3.15.0.jar:?] `

**Comment by jradcliff** [comment]
Hi,

This was identified previously in issue #145, and I released a fix for it in version [v3.15.1](https://github.com/googleads/googleads-java-lib/releases/tag/3.15.1).

Please try upgrading to `3.15.1` and reopen issue #145 if you still encounter unmarshalling problems.

Thanks,
Josh, AdWords API Team
