### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.commons.logging.LogFactory.getClassLoader

### ISSUE THREAD

**Issue by inf3cti0n95** [googleads/googleads-java-lib#147]
I am getting this NoSuchMethodError. I am missing some dependency, but I don't know what I am missing. Tried out all the commons-logging Dependency. I am using this Library along with Spring Boot.

```java.lang.NoSuchMethodError: org.apache.commons.logging.LogFactory.getClassLoader(Ljava/lang/Class;)Ljava/lang/ClassLoader;
	at org.apache.commons.logging.impl.LogFactoryImpl.getClassLoader(LogFactoryImpl.java:447) ~[commons-logging-1.1.1.jar:5.0.4.RELEASE]
	at org.apache.commons.logging.impl.LogFactoryImpl.initDiagnostics(LogFactoryImpl.java:476) ~[commons-logging-1.1.1.jar:5.0.4.RELEASE]
	at org.apache.commons.logging.impl.LogFactoryImpl.<init>(LogFactoryImpl.java:95) ~[commons-logging-1.1.1.jar:5.0.4.RELEASE]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_171]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_171]
	at org.apache.commons.discovery.tools.ClassUtils.newInstance(ClassUtils.java:112) ~[commons-discovery-0.4.jar:0.4]
	at org.apache.commons.discovery.tools.SPInterface.newInstance(SPInterface.java:152) ~[commons-discovery-0.4.jar:0.4]
	at org.apache.commons.discovery.tools.DiscoverClass.newInstance(DiscoverClass.java:534) ~[commons-discovery-0.4.jar:0.4]
	at org.apache.commons.discovery.tools.DiscoverSingleton.find(DiscoverSingleton.java:373) ~[commons-discovery-0.4.jar:0.4]
	at org.apache.commons.discovery.tools.DiscoverSingleton.find(DiscoverSingleton.java:333) ~[commons-discovery-0.4.jar:0.4]
	at org.apache.axis.components.logger.LogFactory$1.run(LogFactory.java:45) ~[axis-1.4.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_171]
	at org.apache.axis.components.logger.LogFactory.getLogFactory(LogFactory.java:41) ~[axis-1.4.jar:na]
	at org.apache.axis.components.logger.LogFactory.<clinit>(LogFactory.java:33) ~[axis-1.4.jar:na]
	at org.apache.axis.configuration.EngineConfigurationFactoryDefault.<clinit>(EngineConfigurationFactoryDefault.java:43) ~[axis-1.4.jar:na]
	at com.google.api.ads.common.lib.soap.axis.conf.AdsAxisEngineConfigurationFactory.<init>(AdsAxisEngineConfigurationFactory.java:41) ~[ads-lib-axis-3.15.1.jar:na]
	at com.google.api.ads.common.lib.soap.axis.conf.AdsAxisEngineConfigurationFactory$$FastClassByGuice$$d9752c39.newInstance(<generated>) ~[guice-4.0.jar:na]
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) ~[guice-4.0.jar:na]
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) ~[guice-4.0.jar:na]
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56) ~[guice-4.0.jar:na]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[guice-4.0.jar:na]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) ~[guice-4.0.jar:na]
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.0.jar:na]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[guice-4.0.jar:na]
	at com.google.inject.Guice.createInjector(Guice.java:96) ~[guice-4.0.jar:na]
	at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice-4.0.jar:na]
	at com.google.inject.Guice.createInjector(Guice.java:62) ~[guice-4.0.jar:na]
	at com.google.api.ads.adwords.axis.factory.AdWordsServices.<clinit>(AdWordsServices.java:45) ~[adwords-axis-3.15.1.jar:na]```

**Comment by jradcliff** [comment]
Hi,

I found [this discussion](https://developer.ibm.com/answers/questions/275538/commons-logging-111-in-application-is-conflicting/) about Axis and Commons Logging dependencies that may be helpful.

Are you using Maven to configure your dependencies, or adding the jars manually? If you're using Maven, please check the output from `mvn dependency:list` to see if there are multiple, conflicting versions of `commons-logging:commons-logging:jar` in the output.

Thanks,
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

It's been a while since I received an update on this, so I'll close it out. Feel free to reopen if you're still encountering issues.

Thanks,
Josh, AdWords API Team

**Comment by cbia4** [comment]
Hi @jradcliff 
I am encountering this problem as well. These are the dependencies included in my project. 

[INFO]    org.springframework.boot:spring-boot-starter-logging:jar:2.0.5.RELEASE:compile
[INFO]    ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO]    ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO]    org.apache.logging.log4j:log4j-to-slf4j:jar:2.10.0:compile
[INFO]    org.apache.logging.log4j:log4j-api:jar:2.10.0:compile
[INFO]    commons-logging:commons-logging:jar:1.1.1:compile

I checked out the discussion post you mentioned above but I'm not convinced programmatically changing my classloader is a sustainable solution for production code.... it appears there is only one version of the commons-logging library being used as a dependency. 

Any other ideas here?

**Comment by cbia4** [comment]
This can be resolved by simply adding the following dependency to your pom:

		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.1.1</version>
		</dependency>

**Comment by jradcliff** [comment]
Hi @cbia4 ,

Thanks for the update. Was that a suggestion for users of the library to add it to _their_ project poms if this conflict occurs, or were you suggesting that I add this dependency to the _library_ project pom(s)?

I hesitate to do the latter because there is no code I've found in the library that directly depends on `commons-logging`. If there is a library dependency **X** that has its own dependencies, **X** should declare those dependencies, as its up to **X** to determine what's required for that artifact. Otherwise, the library would have to declare the entire dependency tree of all dependencies, dependencies of dependencies, dependencies of dependencies of dependencies, and so on.

Thanks,
Josh, AdWords API Team

**Comment by cbia4** [comment]
@jradcliff

I resolved the issue by adding commons-logging to my project dependencies. There appears to be some version conflict with the spring boot dependencies I am using, but by specifying the version AdWords was complaining about the NoSuchMethodError is gone. 

To your point about AdWords not being dependent on commons logging, the error occurs inside the guice framework, not too familiar considering it’s an internal framework but there is something funky with the dependency injection that occurs when AdWordsServices.getInstance() is invoked.

**Comment by thakorji007** [comment]
Hello sir , i had follow all the things which you all are describe here , but event though my problem can not been solved , please help me for the better solution

**Comment by nwbirnie** [comment]
@thakorji007 this issue is a year old. Please open a new issue to discuss this. Include the logs when running on your system, together with the output of `mvn dependency:tree -f path/to/your/pom.xml`.
