### ISSUE TITLE
The tutorial link for uploading the video does not exist

### ISSUE THREAD

**Issue by monkeyWie** [googleads/googleads-java-lib#159]
I found a tutorial link to upload the video in the [documentation](https://developers.google.com/adwords/api/docs/samples/java/miscellaneous), but the link has expired.
The link: http://adwords.google.com/support/aw/bin/answer.py?hl=en&answer=39454

So how do I upload a YouTube video using adwords API?

**Comment by monkeyWie** [comment]
Thanks for your replay, I have tried running the following code,but no success:
```java
MediaServiceInterface mediaService = adWordsServices.get(session, MediaServiceInterface.class);
Video video = new Video();
video.setYouTubeVideoIdString("PFOtvHtyW8s");
Media[] result = mediaService.upload(new Media[]{video});
```

The excpetion:
```
ApiException{applicationExceptionType=ApiException, errors=[MediaError{apiErrorType=MediaError, errorString=MediaError.UNSUPPORTED_TYPE, fieldPath=media[0], fieldPathElements=[FieldPathElement{field=media, index=0}], reason=UNSUPPORTED_TYPE, trigger=}]}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.axis.encoding.ser.BeanDeserializer.<init>(BeanDeserializer.java:104)
	at org.apache.axis.encoding.ser.BeanDeserializer.<init>(BeanDeserializer.java:90)
	at com.google.api.ads.adwords.axis.v201809.cm.ApiException.getDeserializer(ApiException.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.axis.encoding.ser.BaseDeserializerFactory.getSpecialized(BaseDeserializerFactory.java:154)
	at org.apache.axis.encoding.ser.BaseDeserializerFactory.getDeserializerAs(BaseDeserializerFactory.java:84)
	at org.apache.axis.encoding.DeserializationContext.getDeserializer(DeserializationContext.java:464)
	at org.apache.axis.encoding.DeserializationContext.getDeserializerForType(DeserializationContext.java:547)
	at org.apache.axis.message.SOAPFaultDetailsBuilder.onStartChild(SOAPFaultDetailsBuilder.java:157)
	at org.apache.axis.encoding.DeserializationContext.startElement(DeserializationContext.java:1035)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.apache.axis.encoding.DeserializationContext.parse(DeserializationContext.java:227)
	at org.apache.axis.SOAPPart.getAsSOAPEnvelope(SOAPPart.java:696)
	at org.apache.axis.Message.getSOAPEnvelope(Message.java:435)
	at org.apache.axis.transport.http.HTTPSender.readFromSocket(HTTPSender.java:796)
	at org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:144)
	at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
	at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
	at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
	at org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
	at org.apache.axis.client.Call.invokeEngine(Call.java:2784)
	at org.apache.axis.client.Call.invoke(Call.java:2767)
	at org.apache.axis.client.Call.invoke(Call.java:2443)
	at org.apache.axis.client.Call.invoke(Call.java:2366)
	at org.apache.axis.client.Call.invoke(Call.java:1812)
	at com.google.api.ads.adwords.axis.v201809.cm.MediaServiceSoapBindingStub.upload(MediaServiceSoapBindingStub.java:886)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.api.ads.common.lib.soap.SoapClientHandler.invoke(SoapClientHandler.java:100)
	at com.google.api.ads.common.lib.soap.axis.AxisHandler.invokeSoapCall(AxisHandler.java:234)
	at com.google.api.ads.common.lib.soap.SoapServiceClient.callSoapClient(SoapServiceClient.java:63)
	at com.google.api.ads.common.lib.soap.SoapServiceClient.invoke(SoapServiceClient.java:93)
```

**Comment by nwbirnie** [comment]
Sorry correction here, the only place you can use Youtube Videos is GmailAd. For this creative type you have to create the Video via the [Google Ads UI](ads.google.com) or [Scripts](https://developers.google.com/google-ads/scripts/) (link to [reference docs](https://developers.google.com/google-ads/scripts/docs/reference/adwordsapp/adwordsapp_media)).
