### ISSUE TITLE
(502)Bad Gateway

### ISSUE THREAD

**Issue by mattareddym** [googleads/googleads-java-lib#171]
Hi,
I am seeing below issues frequently from last couple of days while trying to invoke readUserList and mutateMembers respectively. Could you please help me with what can cause this?
1) Caused by: (502)Bad Gateway
--
  | at org.apache.axis.transport.http.HTTPSender.readFromSocket(HTTPSender.java:744)
  | at org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:144)
  | at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
  | at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
  | at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
  | at org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
  | at org.apache.axis.client.Call.invokeEngine(Call.java:2784)
  | at org.apache.axis.client.Call.invoke(Call.java:2767)
  | at org.apache.axis.client.Call.invoke(Call.java:2443)
  | at org.apache.axis.client.Call.invoke(Call.java:2366)
  | at org.apache.axis.client.Call.invoke(Call.java:1812)
  | at com.google.api.ads.adwords.axis.v201809.rm.AdwordsUserListServiceSoapBindingStub.get(AdwordsUserListServiceSoapBindingStub.java:1091)
  | at sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at com.google.api.ads.common.lib.soap.SoapClientHandler.invoke(SoapClientHandler.java:100)
  | at com.google.api.ads.common.lib.soap.axis.AxisHandler.invokeSoapCall(AxisHandler.java:234)
  | at com.google.api.ads.common.lib.soap.SoapServiceClient.callSoapClient(SoapServiceClient.java:63)
  | at com.google.api.ads.common.lib.soap.SoapServiceClient.invoke(SoapServiceClient.java:93)
  | at com.sun.proxy.$Proxy90.get(Unknown Source)

2) org.apache.axis.AxisFault: (502)Bad Gateway
	at org.apache.axis.transport.http.HTTPSender.readFromSocket(HTTPSender.java:744) ~[axis-1.4.jar:?]
	at org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:144) ~[axis-1.4.jar:?]
	at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32) ~[axis-1.4.jar:?]
	at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118) ~[axis-1.4.jar:?]
	at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83) ~[axis-1.4.jar:?]
	at org.apache.axis.client.AxisClient.invoke(AxisClient.java:165) ~[axis-1.4.jar:?]
	at org.apache.axis.client.Call.invokeEngine(Call.java:2784) ~[axis-1.4.jar:?]
	at org.apache.axis.client.Call.invoke(Call.java:2767) ~[axis-1.4.jar:?]
	at org.apache.axis.client.Call.invoke(Call.java:2443) ~[axis-1.4.jar:?]
	at org.apache.axis.client.Call.invoke(Call.java:2366) ~[axis-1.4.jar:?]
	at org.apache.axis.client.Call.invoke(Call.java:1812) ~[axis-1.4.jar:?]
	at com.google.api.ads.adwords.axis.v201809.rm.AdwordsUserListServiceSoapBindingStub.mutateMembers(AdwordsUserListServiceSoapBindingStub.java:1175) ~[adwords-axis-4.1.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor337.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.google.api.ads.common.lib.soap.SoapClientHandler.invoke(SoapClientHandler.java:100) ~[ads-lib-4.1.0.jar:?]
	at com.google.api.ads.common.lib.soap.axis.AxisHandler.invokeSoapCall(AxisHandler.java:234) ~[ads-lib-axis-4.1.0.jar:?]
	at com.google.api.ads.common.lib.soap.SoapServiceClient.callSoapClient(SoapServiceClient.java:63) ~[ads-lib-4.1.0.jar:?]
	at com.google.api.ads.common.lib.soap.SoapServiceClient.invoke(SoapServiceClient.java:93) ~[ads-lib-4.1.0.jar:?]
	at com.sun.proxy.$Proxy98.mutateMembers(Unknown Source) ~[?:?]

**Comment by nwbirnie** [comment]
This is most likely not related to the Java client library. Pleas ask on the [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api).
