### ISSUE TITLE
Socket timeout when using AdServiceInterface.mutate()

### ISSUE THREAD

**Issue by markusheiden** [googleads/googleads-java-lib#176]
I am updating many (100000+) expanded text ads via the AdServiceInterface.mutate() method.
Most requests are successful, but some always run in a socket timeout error.
I already tried to reduce the number of operations per request from 2000 to 500, but this did not solve the problem.
Are there any recommendations for this or is this an AdWords API or API client failure?

Stacktraces:

```
o.a.a.SOAPPart#getAsBytes|Exception:
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
        at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
        at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823) ~[?:?]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:252) ~[?:?]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:292) ~[?:?]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:351) ~[?:?]
        at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[?:?]
        at org.apache.axis.SOAPPart.getAsBytes(SOAPPart.java:453) ~[axis-1.4.jar!/:?]
        at org.apache.axis.SOAPPart.getAsString(SOAPPart.java:559) ~[axis-1.4.jar!/:?]
        at org.apache.axis.SOAPPart.writeTo(SOAPPart.java:322) ~[axis-1.4.jar!/:?]
        at org.apache.axis.SOAPPart.writeTo(SOAPPart.java:269) ~[axis-1.4.jar!/:?]
        at org.apache.axis.Message.writeTo(Message.java:539) ~[axis-1.4.jar!/:?]
        at com.google.api.ads.common.lib.soap.ResponseInfoXPathSet.parseMessage(ResponseInfoXPathSet.java:76) ~[ads-lib-4.6.0.jar!/:?]
        at com.google.api.ads.common.lib.soap.axis.AxisHandler.invokeSoapCall(AxisHandler.java:249) ~[ads-lib-axis-4.6.0.jar!/:?]
        at com.google.api.ads.common.lib.soap.SoapServiceClient.callSoapClient(SoapServiceClient.java:63) ~[ads-lib-4.6.0.jar!/:?]
        at com.google.api.ads.common.lib.soap.SoapServiceClient.invoke(SoapServiceClient.java:93) ~[ads-lib-4.6.0.jar!/:?]
        at com.sun.proxy.$Proxy261.mutate(Unknown Source) ~[?:?]
```

```
o.a.a.SOAPPart#getAsString|Cannot convert form 2 to String
```

```
java.lang.NullPointerException: null
        at org.apache.axis.SOAPPart.writeTo(SOAPPart.java:324) ~[axis-1.4.jar!/:?]
        at org.apache.axis.SOAPPart.writeTo(SOAPPart.java:269) ~[axis-1.4.jar!/:?]
        at org.apache.axis.Message.writeTo(Message.java:539) ~[axis-1.4.jar!/:?]
        at com.google.api.ads.common.lib.soap.ResponseInfoXPathSet.parseMessage(ResponseInfoXPathSet.java:76) ~[ads-lib-4.6.0.jar!/:?]
        at com.google.api.ads.common.lib.soap.axis.AxisHandler.invokeSoapCall(AxisHandler.java:249) ~[ads-lib-axis-4.6.0.jar!/:?]
        at com.google.api.ads.common.lib.soap.SoapServiceClient.callSoapClient(SoapServiceClient.java:63) ~[ads-lib-4.6.0.jar!/:?]
        at com.google.api.ads.common.lib.soap.SoapServiceClient.invoke(SoapServiceClient.java:93) ~[ads-lib-4.6.0.jar!/:?]
        at com.sun.proxy.$Proxy261.mutate(Unknown Source) ~[?:?]
```

**Comment by nwbirnie** [comment]
It's possible that you're sending requests too quickly and that some connections get closed by the server without warning.

Could you try the same requests, but spacing them apart, say fewer than 10 per second and see if that resolves the issue?

**Comment by markusheiden** [comment]
We do batching with the same rates since years and never got problems. Since we added updating ads via the AdService these problems occur (before we delete/re-created them instead). So I don't think it's a matter of rates, but somehow related to the AdService.

I will try whether spacing will help. But we need to still do parallel access to different accounts to achieve reasonable execution times.

**Comment by nwbirnie** [comment]
Another possibility, since the error message is "Read timed out" it's possible that you have modified the timeout settings for the API client. Can you check your configuration for the entry `api.adwords.soapRequestTimeout`?

**Comment by markusheiden** [comment]
We did not change any setting. The request times out after ~40 minutes. 

Other accounts executing similar requests in similar amounts do not show this problem. So I assume it is some data that let the Google Ads server fail fatally. What can I do to help you to analyze and fix the underlying problem? If there is any kind of problem with my requests, I at least expect to get an ApiError with the cause.

Anyway the stone aged axis 1.4 dependency makes it very hard to detect this kind of failure and react to it. Axis swallows the original SocketTimeoutException and later on fails with a NullPointerException due to missing data. Is there any plan to update from axis 1 to axis 2 or any other maintained SOAP library?

**Comment by nwbirnie** [comment]
Hey, let's take a look at the request logs on our side to see if something fails on the backend. Can you grab the full SOAP logs for the request, synchronize your machine's clock with NTP, and include the timestamp so I can match them up in lieu of a requestId (returned in the API response).

Regarding Axis versions, this is not currently something we're planning on doing. Reason being that we're moving towards Google Ads API as a replacement for AWAPI. Timelines have recently moved slightly further out for completing this migration, due to the extended beta period on GAAPI. However, our main focus remains to phase out AWAPI (and the entire SOAP stack) so we want to avoid spending expensive engineering effort on technology which is EOL. Of course we would reassess if it turns out that Axis 1.4 is causing issues significant issues, though I doubt that the issue we're seeing here is a problem with the client-side SOAP stack.

**Comment by Svhorsch** [comment]
Hey there,
we are also facing this problem, but in our case it is the `mutate` on the `AdGroupCriterionServiceInterface`.
Here the stacktrace:
```
Caused by: java.lang.NullPointerException
    at org.apache.axis.SOAPPart.writeTo(SOAPPart.java:324)
    at org.apache.axis.SOAPPart.writeTo(SOAPPart.java:269)
    at org.apache.axis.Message.writeTo(Message.java:539)
    at com.google.api.ads.common.lib.soap.ResponseInfoXPathSet.parseMessage(ResponseInfoXPathSet.java:76)
    at com.google.api.ads.common.lib.soap.axis.AxisHandler.invokeSoapCall(AxisHandler.java:249)
    at com.google.api.ads.common.lib.soap.SoapServiceClient.callSoapClient(SoapServiceClient.java:63)
    at com.google.api.ads.common.lib.soap.SoapServiceClient.invoke(SoapServiceClient.java:93)
    at com.sun.proxy.$Proxy371.mutate(Unknown Source)
    at com.google.api.ads.adwords.axis.v201809.cm.AdGroupCriterionServiceInterface$mutate.call(Unknown Source)
```

We already turned on the api logs but the response is not in there, cause it seems like that the response is written to the logs after the message is parsed, which seems to be the problem.
The last time we faced that was on Thursday, 11. July 2019 08:45:37 (GMT)

**Comment by christopherseeley** [comment]
AdWords API has been turned down and replaced by the Google Ads API. Closing as stale.
