### ISSUE TITLE
Exception while using Java 11

### ISSUE THREAD

**Issue by alphawolf1988** [googleads/googleads-java-lib#180]
I'm getting the following exception, if i use the library with Java 11:

`
Caused by: java.lang.NoClassDefFoundError: javax/xml/soap/SOAPHeaderElement
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:115)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:706)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:930)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:852)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:291)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:222)
	at com.google.inject.internal.InjectorImpl.createParameterInjector(InjectorImpl.java:991)
	at com.google.inject.internal.InjectorImpl.getParametersInjectors(InjectorImpl.java:978)
	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:69)
	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
	at com.google.inject.internal.FailableCache$1.load(FailableCache.java:40)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	... 56 more
Caused by: java.lang.ClassNotFoundException: javax.xml.soap.SOAPHeaderElement
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 77 more

`

**Comment by Raibaz** [comment]
Hi, 

This really looks like an issue with the Java EE modules that are no longer endorsed in the JDK since Java 9.

Can you please provide more information on how to reproduce this? What are you executing when this exception is thrown?

Thanks,
Mattia

**Comment by nwbirnie** [comment]
It looks like we missed the fact that JDK 9 enables SOAP via modules, but JDK 11 [removes SOAP support entirely](http://openjdk.java.net/jeps/320). Therefore the following dependency needs to be added to restore SOAP classes.

```
    <dependency>
      <groupId>javax.xml.soap</groupId>
      <artifactId>javax.xml.soap-api</artifactId>
      <version>1.4.0</version>
    </dependency>
```

I'll send an update out shortly for this, apologies for the inconvenience.
