### ISSUE TITLE
Invalid element in com.google.api.ads.admanager.axis.v202211.ReportQuery - timeZoneType

### ISSUE THREAD

**Issue by haibau** [googleads/googleads-java-lib#248]
We have a daily job using the Java client that uses API v202211 to retrieve a month-to-date report, and it has been running fine for a month, up until this afternoon.
This error is:
`rg.xml.sax.SAXException: Invalid element in com.google.api.ads.admanager.axis.v202211.ReportQuery - timeZoneType
	at org.apache.axis.AxisFault.makeFault(AxisFault.java:101)
	at org.apache.axis.client.Call.invoke(Call.java:2470)
	at org.apache.axis.client.Call.invoke(Call.java:2366)
	at org.apache.axis.client.Call.invoke(Call.java:1812)
	at com.google.api.ads.admanager.axis.v202211.ReportServiceSoapBindingStub.runReportJob(ReportServiceSoapBindingStub.java:907)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.api.ads.common.lib.soap.SoapClientHandler.invoke(SoapClientHandler.java:100)
	at com.google.api.ads.common.lib.soap.axis.AxisHandler.invokeSoapCall(AxisHandler.java:234)
	at com.google.api.ads.common.lib.soap.SoapServiceClient.callSoapClient(SoapServiceClient.java:63)
	at com.google.api.ads.common.lib.soap.SoapServiceClient.invoke(SoapServiceClient.java:93)
	at com.sun.proxy.$Proxy141.runReportJob(Unknown Source)`

**Comment by lfscheidegger** [comment]
We are also running into the same issue, and there are a few messages in the forum since yesterday reporting the same issue as well ([here](https://groups.google.com/g/google-doubleclick-for-publishers-api/c/MTIf-GmFKeE), [here](https://groups.google.com/g/google-doubleclick-for-publishers-api/c/_WcaPQwDAyk), [here](https://groups.google.com/g/google-doubleclick-for-publishers-api/c/ghzd_dHiPt0)).

@jradcliff apologies for mentioning you out of the blue, but this appears similar to [this other issue](https://github.com/googleads/googleads-java-lib/issues/60) back from 2016, where WSDLs for published versions of the API had been inadvertently changed. Any chance this could be something similar? Thank you!

**Comment by haibau** [comment]
@lfscheidegger ,
I temporarily switched to v202202 and it worked, but I have to modify some functions in the source code. 
Hopefully Google will soon release a new version to fix the above error.

**Comment by jradcliff** [comment]
Hi,

We're aware of this issue and the team's working on a fix to the API to resolve it. I don't expect that fix to require any client library changes or changes to anyone's usage.

Thanks,
Josh

**Comment by lfscheidegger** [comment]
Thanks @jradcliff ! Do you have an estimate on ETA for the fix?

**Comment by haibau** [comment]
@jradcliff @lfscheidegger 
Thanks, this bug has been fixed on  V202211 version.
