### ISSUE TITLE
Goggle Ads API v14-java.lang.NoSuchMethodError: com.google.api.client.util.escape.PercentEscaper.<init>(Ljava/lang/String;)V

### ISSUE THREAD

**Issue by saurabhsumanbbsr** [googleads/googleads-java-lib#264]
While testing GetCampaigns operation using v14 ads api in java  we are getting the below error .We are using pom dependency as below	<dependency>
		<groupId>com.google.api-ads</groupId>
		<artifactId>google-ads</artifactId>
		<version>26.0.0</version>
	</dependency>

**Error**:
2023-07-27 16:25:19,938 ERROR [main] A: C: AccountDownloadTask:78 - com.google.api.client.util.escape.PercentEscaper.<init>(Ljava/lang/String;)V
**java.lang.NoSuchMethodError: com.google.api.client.util.escape.PercentEscaper.<init>(Ljava/lang/String;)V**
	at com.google.api.gax.rpc.RequestUrlParamsEncoder.<clinit>(RequestUrlParamsEncoder.java:47)
	at com.google.api.gax.grpc.GrpcUnaryRequestParamCallable.<init>(GrpcUnaryRequestParamCallable.java:54)
	at com.google.api.gax.grpc.GrpcRawCallableFactory.createUnaryCallable(GrpcRawCallableFactory.java:59)
	at com.google.api.gax.grpc.GrpcCallableFactory.createBaseUnaryCallable(GrpcCallableFactory.java:85)
	at com.google.ads.googleads.lib.GrpcGoogleAdsCallableFactory.createBaseUnaryCallable(GrpcGoogleAdsCallableFactory.java:70)
	at com.google.ads.googleads.lib.GrpcGoogleAdsCallableFactory.createUnaryCallable(GrpcGoogleAdsCallableFactory.java:80)
	at com.google.longrunning.stub.GrpcOperationsStub.<init>(GrpcOperationsStub.java:226)
	at com.google.longrunning.stub.GrpcOperationsStub.create(GrpcOperationsStub.java:133)
	at com.google.ads.googleads.v14.services.stub.GrpcGoogleAdsServiceStub.<init>(GrpcGoogleAdsServiceStub.java:132)
	at com.google.ads.googleads.v14.services.stub.GrpcGoogleAdsServiceStub.<init>(GrpcGoogleAdsServiceStub.java:118)
	at com.google.ads.googleads.v14.services.stub.GrpcGoogleAdsServiceStub.create(GrpcGoogleAdsServiceStub.java:96)
	at com.google.ads.googleads.v14.services.stub.GoogleAdsServiceStubSettings.createStub(GoogleAdsServiceStubSettings.java:189)
	at com.google.ads.googleads.v14.services.GoogleAdsServiceClient.<init>(GoogleAdsServiceClient.java:150)
	at com.google.ads.googleads.v14.services.GoogleAdsServiceClient.create(GoogleAdsServiceClient.java:132)
	at com.google.ads.googleads.lib.catalog.GeneratedCatalog$V14Client.createGoogleAdsServiceClient(GeneratedCatalog.java:4594)

**Comment by saurabhsumanbbsr** [comment]
Any updates on the above issue.

**Comment by jradcliff** [comment]
Closing this issue because it is for the google-ads-java repository and duplicates https://github.com/googleads/google-ads-java/issues/724 there.
