### ISSUE TITLE
Error on Running DFPSession [INSERT_APPLICATION_NAME]

### ISSUE THREAD

**Issue by plammy** [googleads/googleads-java-lib#34]
Hello everbody,

i'm using dfp-axis-1.33 with Eclipse. I can run the file GetRefreshTokenWithoutPropertiesFile.java and recieve refreshToken, but when I run the file CreateDfpSessionWithoutPropertiesFile.java I recieve following exception:

Exception in thread "main" Application name must be set and not be the default [INSERT_APPLICATION_NAME_HERE] caused by: [applicationName]
	at com.google.api.ads.dfp.lib.client.DfpSession$Builder.validate(DfpSession.java:332)
	at com.google.api.ads.dfp.lib.client.DfpSession$Builder.build(DfpSession.java:305)
	at dfp.axis.auth.CreateDfpSessionWithoutPropertiesFile.createDfpSession(CreateDfpSessionWithoutPropertiesFile.java:53)
	at dfp.axis.auth.CreateDfpSessionWithoutPropertiesFile.main(CreateDfpSessionWithoutPropertiesFile.java:82)

Where must I fill the applicationName? I have already filled this in the ads.properties but I don't use this.

Kind regards
PM

**Comment by Narwalter** [comment]
Since you're not using the ads.properties file, you'll need to explicitly set your application name and network code for the Session. See [withApplicationName](https://github.com/googleads/googleads-java-lib/blob/1.36.0/modules/ads_lib/src/main/java/com/google/api/ads/dfp/lib/client/DfpSession.java#L274) and [withNetworkCode](https://github.com/googleads/googleads-java-lib/blob/1.36.0/modules/ads_lib/src/main/java/com/google/api/ads/dfp/lib/client/DfpSession.java#L266).

I'll leave this issue open until the example is updated.

**Comment by plammy** [comment]
I use this file https://github.com/googleads/googleads-java-lib/blob/1.36.0/examples/dfp_axis/src/main/java/dfp/axis/auth/CreateDfpSessionWithoutPropertiesFile.java and I try to modify this part

 private static DfpSession createDfpSession(String clientId, String clientSecret,
      String refreshToken) throws OAuthException,
      ValidationException {
    .................

    // Create a new DfpSession without using a properties file.
    return new DfpSession.Builder()
    	.withApplicationName(APPLICATION_NAME)
        .withOAuth2Credential(credential)
        .build();
  }


But it still through exception:

AxisFault
 faultCode: {http://schemas.xmlsoap.org/soap/envelope/}Server.userException
 faultSubcode: 
 faultString: java.net.ConnectException: Connection timed out: connect
 faultActor: 
 faultNode: 
 faultDetail: 
	{http://xml.apache.org/axis/}stackTrace:java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:649)
	at sun.security.ssl.SSLSocketImpl.&lt;init&gt;(SSLSocketImpl.java:409)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
	at org.apache.axis.components.net.JSSESocketFactory.create(JSSESocketFactory.java:92)
	at org.apache.axis.transport.http.HTTPSender.getSocket(HTTPSender.java:191)
	at org.apache.axis.transport.http.HTTPSender.writeToSocket(HTTPSender.java:404)



Kind regards
PM

**Comment by Narwalter** [comment]
Can you please start a new thread in the [DFP API forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api)? That's a more appropriate channel for support than the issue tracker.

**Comment by jradcliff** [comment]
Closing per the previous comment.
