### ISSUE TITLE
org.xml.sax.SAXException: Invalid element in com.google.api.ads.adwords.axis.v201509.cm.ReportDefinitionField - exclusiveFields

### ISSUE THREAD

**Issue by dpogorelov** [googleads/googleads-java-lib#60]
Hi,

I've got the following error message on the latest 2.8.0 googleads-java-lib release:
15:54:01,671 ERROR [org.apache.axis.client.Call] (Worker1_QueryProcessorQueue25) Exception:: org.xml.sax.SAXException: Invalid element in com.google.api.ads.adwords.axis.v201509.cm.ReportDefinitionField - exclusiveFields
        at org.apache.axis.encoding.ser.BeanDeserializer.onStartChild(BeanDeserializer.java:258)
        at org.apache.axis.encoding.DeserializationContext.startElement(DeserializationContext.java:1035)
        at org.apache.axis.message.SAX2EventRecorder.replay(SAX2EventRecorder.java:165)
        at org.apache.axis.message.MessageElement.publishToHandler(MessageElement.java:1141)
        at org.apache.axis.message.RPCElement.deserialize(RPCElement.java:236)
        at org.apache.axis.message.RPCElement.getParams(RPCElement.java:384)
        at org.apache.axis.client.Call.invoke(Call.java:2467)
        at org.apache.axis.client.Call.invoke(Call.java:2366)
        at org.apache.axis.client.Call.invoke(Call.java:1812)
        at com.google.api.ads.adwords.axis.v201509.cm.ReportDefinitionServiceSoapBindingStub.getReportFields(ReportDefinitionServiceSoapBindingStub.java:549)

I've checked source code of the lib and noticed that the exclusiveFields was skipped in adwords axis v201509 though according to the https://developers.google.com/adwords/api/docs/reference/v201509/ReportDefinitionService.ReportDefinitionField documentation the exclusiveFields must be there. Please could you check it again and fix it accordingly.
Seems the problem goes from https://adwords.google.com/api/adwords/cm/v201509/ReportDefinitionService?wsdl - the exclusiveFields is not provided there.
Thank you.

**Comment by jradcliff** [comment]
Thanks for pointing this out. It looks like this was an inadvertent change -- we don't usually change WSDLs for released versions. I'm following up on this and will post an update here as soon as I have more information.

Thanks,
Josh, AdWords API Team

**Comment by dpogorelov** [comment]
Hi Josh,
no problem. Please post any info here if you can fix the bug. We should get the fix as soon as possible. Now we can't work with the v201509 api, but we can use the v201506 but it will be deprecated on 11th of April, 2016. So, we have just 2-3 months.

Thank you.

**Comment by jradcliff** [comment]
Hi,

Thanks for bearing with us -- this issue should now be resolved and you should no longer see the `exclusivePairs` field in your XML response. Please reopen this issue if the problem persists.

Thanks,
Josh, AdWords API Team

**Comment by dpogorelov** [comment]
Hi Josh,

I confirm that the bug related to the exclusiveFields has disappeared.
Thanks a lot.
