### ISSUE TITLE
Encountered a problem reading the provided configuration file "ads.properties"

### ISSUE THREAD

**Issue by vdnhat** [googleads/googleads-java-lib#73]
Hi everyone,

I used google api-ads version 2.12.0 for DFP but this show error such as:

```
Caused by: java.lang.IllegalArgumentException: Encountered a problem reading the provided configuration file "ads.properties"!
	at com.google.api.ads.common.lib.conf.ConfigurationHelper.fromFile(com.google.api.ads.common.lib.conf.ConfigurationHelper:42)
	at com.google.api.ads.common.lib.factory.FactoryConfiguration$Builder.fromFile(com.google.api.ads.common.lib.factory.FactoryConfiguration:85)
	at com.google.api.ads.common.lib.factory.FactoryConfiguration$Builder.fromFile(com.google.api.ads.common.lib.factory.FactoryConfiguration:78)
	at com.google.api.ads.common.lib.AdsModule.<init>(com.google.api.ads.common.lib.AdsModule:57)
	at com.google.api.ads.adwords.lib.AdWordsModule.<init>(AdWordsModule.java:31)
	at com.google.api.ads.adwords.lib.utils.AdWordsInternals.<clinit>(AdWordsInternals.java:34)
	... 34 more
Caused by: org.apache.commons.configuration.ConfigurationException: Cannot locate configuration source ads.properties
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:259)
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:238)
	at org.apache.commons.configuration.AbstractFileConfiguration.<init>(AbstractFileConfiguration.java:158)
	at org.apache.commons.configuration.PropertiesConfiguration.<init>(PropertiesConfiguration.java:253)
	at com.google.api.ads.common.lib.conf.ConfigurationHelper.fromFile(com.google.api.ads.common.lib.conf.ConfigurationHelper:40)
	... 39 more


```
  
This is my code

	        ```
                String clientId = dfpSite.getClientId();
		String clientSecret = dfpSite.getSecretKey();
		String refreshToken = dfpSite.getRefreshToken(); 
		String networkCode = dfpSite.getNetworkCode();      
		
			// Generate a refreshable OAuth2 credential.
			Credential oAuth2Credential = new OfflineCredentials.Builder().forApi(Api.DFP).withClientSecrets(clientId, clientSecret) 
					.withRefreshToken(refreshToken).build().generateCredential();
	
			// Construct a DfpSession.
			DfpSession session = new DfpSession.Builder() 
					.withApplicationName("MY_APP_" + dfpSite.getSiteId() ).withNetworkCode(networkCode)
					.withOAuth2Credential(oAuth2Credential).build();
```
	

I don't know what is happen ?

**Comment by vdnhat** [comment]
After debug. It conflict with library: common-0.4.0.jar . This version info:
Built-By: arogal
Build-Jdk: 1.6.0-google-v4
