### ISSUE TITLE
creating_and_serving_video_ads getting Exception for v201411

### ISSUE THREAD

**Issue by arishvarunmishra** [googleads/googleads-java-lib#86]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.google.dfp.examples.CreateVideoRedirectCreatives.main(CreateVideoRedirectCreatives.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for com.google.api.ads.common.lib.client.HeaderHandler<com.google.api.ads.dfp.lib.client.DfpSession, com.google.api.ads.dfp.lib.client.DfpServiceDescriptor> was bound.
  while locating com.google.api.ads.common.lib.client.HeaderHandler<com.google.api.ads.dfp.lib.client.DfpSession, com.google.api.ads.dfp.lib.client.DfpServiceDescriptor>
    for parameter 4 at com.google.api.ads.dfp.lib.client.DfpServiceClient.<init>(DfpServiceClient.java:56)
  at com.google.api.ads.common.lib.factory.FactoryModule$AdsServiceClientFactoryInterface.create(FactoryModule.java:1)
  at com.google.inject.assistedinject.FactoryProvider2.initialize(FactoryProvider2.java:660)
  at com.google.inject.assistedinject.FactoryModuleBuilder$1.configure(FactoryModuleBuilder.java:335) (via modules: com.google.api.ads.dfp.jaxws.DfpJaxWsModule -> com.google.api.ads.dfp.lib.DfpSoapModule -> com.google.api.ads.common.lib.factory.FactoryModule -> com.google.inject.assistedinject.FactoryModuleBuilder$1)

**Comment by christopherseeley** [comment]
v201411 has been sunset. You'll need to update the example code to use a newer version, and make sure you have the latest java client library version.
